package vendingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MachineStatus implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String locationType;
   private java.lang.Double productQuantity;
   private java.lang.Double distance;
   private java.lang.String machineStatus;
   private java.lang.String machineStatusColor;

   public MachineStatus()
   {
   }

   public java.lang.String getLocationType()
   {
      return this.locationType;
   }

   public void setLocationType(java.lang.String locationType)
   {
      this.locationType = locationType;
   }

   public java.lang.Double getProductQuantity()
   {
      return this.productQuantity;
   }

   public void setProductQuantity(java.lang.Double productQuantity)
   {
      this.productQuantity = productQuantity;
   }

   public java.lang.Double getDistance()
   {
      return this.distance;
   }

   public void setDistance(java.lang.Double distance)
   {
      this.distance = distance;
   }

   public java.lang.String getMachineStatus()
   {
      return this.machineStatus;
   }

   public void setMachineStatus(java.lang.String machineStatus)
   {
      this.machineStatus = machineStatus;
   }

   public java.lang.String getMachineStatusColor()
   {
      return this.machineStatusColor;
   }

   public void setMachineStatusColor(java.lang.String machineStatusColor)
   {
      this.machineStatusColor = machineStatusColor;
   }

   public MachineStatus(java.lang.String locationType,
         java.lang.Double productQuantity, java.lang.Double distance,
         java.lang.String machineStatus, java.lang.String machineStatusColor)
   {
      this.locationType = locationType;
      this.productQuantity = productQuantity;
      this.distance = distance;
      this.machineStatus = machineStatus;
      this.machineStatusColor = machineStatusColor;
   }

}