package vendingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PriorityRules implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String issueType;
   private java.lang.String locationTier;
   private java.lang.Integer priority;

   public PriorityRules()
   {
   }

   public java.lang.String getIssueType()
   {
      return this.issueType;
   }

   public void setIssueType(java.lang.String issueType)
   {
      this.issueType = issueType;
   }

   public java.lang.String getLocationTier()
   {
      return this.locationTier;
   }

   public void setLocationTier(java.lang.String locationTier)
   {
      this.locationTier = locationTier;
   }

   public java.lang.Integer getPriority()
   {
      return this.priority;
   }

   public void setPriority(java.lang.Integer priority)
   {
      this.priority = priority;
   }

   public PriorityRules(java.lang.String issueType,
         java.lang.String locationTier, java.lang.Integer priority)
   {
      this.issueType = issueType;
      this.locationTier = locationTier;
      this.priority = priority;
   }

}