package vendingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskAssignment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String issueType;
   private java.lang.String locationType;
   private java.lang.Integer technicalLevel;

   public TaskAssignment()
   {
   }

   public java.lang.String getIssueType()
   {
      return this.issueType;
   }

   public void setIssueType(java.lang.String issueType)
   {
      this.issueType = issueType;
   }

   public java.lang.String getLocationType()
   {
      return this.locationType;
   }

   public void setLocationType(java.lang.String locationType)
   {
      this.locationType = locationType;
   }

   public java.lang.Integer getTechnicalLevel()
   {
      return this.technicalLevel;
   }

   public void setTechnicalLevel(java.lang.Integer technicalLevel)
   {
      this.technicalLevel = technicalLevel;
   }

   public TaskAssignment(java.lang.String issueType,
         java.lang.String locationType, java.lang.Integer technicalLevel)
   {
      this.issueType = issueType;
      this.locationType = locationType;
      this.technicalLevel = technicalLevel;
   }

}