package vendingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VendingStatus implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String locationType;
   private java.lang.Double productQuantity;
   private java.lang.Double distance;
   private java.lang.String refillStatus;
   private java.lang.String color;

   public VendingStatus()
   {
   }

   public java.lang.String getLocationType()
   {
      return this.locationType;
   }

   public void setLocationType(java.lang.String locationType)
   {
      this.locationType = locationType;
   }

   public java.lang.Double getProductQuantity()
   {
      return this.productQuantity;
   }

   public void setProductQuantity(java.lang.Double productQuantity)
   {
      this.productQuantity = productQuantity;
   }

   public java.lang.Double getDistance()
   {
      return this.distance;
   }

   public void setDistance(java.lang.Double distance)
   {
      this.distance = distance;
   }

   public java.lang.String getRefillStatus()
   {
      return this.refillStatus;
   }

   public void setRefillStatus(java.lang.String refillStatus)
   {
      this.refillStatus = refillStatus;
   }

   public java.lang.String getColor()
   {
      return this.color;
   }

   public void setColor(java.lang.String color)
   {
      this.color = color;
   }

   public VendingStatus(java.lang.String locationType,
         java.lang.Double productQuantity, java.lang.Double distance,
         java.lang.String refillStatus, java.lang.String color)
   {
      this.locationType = locationType;
      this.productQuantity = productQuantity;
      this.distance = distance;
      this.refillStatus = refillStatus;
      this.color = color;
   }

}